name: flutter_assignment_3
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.20.0
  firebase_auth: ^3.4.2
  cloud_firestore: ^3.3.0
  image_picker: ^0.8.5+3
  firebase_storage: ^10.3.2
  emoji_picker_flutter: ^1.3.0
  flutter_rating_bar: ^4.0.1
  uuid: ^3.0.6

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.0

flutter_icons:
  ios: true
  image_path: "images/chatty.jpeg"


flutter:
  uses-material-design: true
  assets:
    - images/chatty.jpeg
    - images/welcome.gif
