// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHnnDbrAeZp3OFEpGmzS9pGme6WpIFmTY',
    appId: '1:990276348804:web:e9a40f53917ada7b9a4bd1',
    messagingSenderId: '990276348804',
    projectId: 'groupchat-51b94',
    authDomain: 'groupchat-51b94.firebaseapp.com',
    storageBucket: 'groupchat-51b94.appspot.com',
    measurementId: 'G-TKGLWTTRL4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBagLT4FE42VVDiPrTNDIrBinS3Jly3Es0',
    appId: '1:990276348804:android:d9c267352ebaa9ff9a4bd1',
    messagingSenderId: '990276348804',
    projectId: 'groupchat-51b94',
    storageBucket: 'groupchat-51b94.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJz-geIQi5bB_akgtlzKtDMJtwW5J2oHE',
    appId: '1:990276348804:ios:6a7319876232d8109a4bd1',
    messagingSenderId: '990276348804',
    projectId: 'groupchat-51b94',
    storageBucket: 'groupchat-51b94.appspot.com',
    iosClientId: '990276348804-bi1gjkdal8qrf9r0i5tmt6j11qi0go34.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAssignment3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJz-geIQi5bB_akgtlzKtDMJtwW5J2oHE',
    appId: '1:990276348804:ios:6a7319876232d8109a4bd1',
    messagingSenderId: '990276348804',
    projectId: 'groupchat-51b94',
    storageBucket: 'groupchat-51b94.appspot.com',
    iosClientId: '990276348804-bi1gjkdal8qrf9r0i5tmt6j11qi0go34.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAssignment3',
  );
}
